### PR TITLE
Added more sections, resources and features

### PR DESCRIPTION
**Pull request by Samyak-Waghmare**
i have added more sections, resources and features.

Features: Added bottom to top, search functionality and hover effects.

### CODE REVIEW

**Comment by NisooJadhav** [comment]
@Samyak-Waghmare thank you for your contribution!

**Comment by aakarsh-2004** [comment]
Did your PR count in Hacktoberfest @Samyak-Waghmare

**Comment by NisooJadhav** [comment]
@aakarsh-2004 Yes, the repo & PRs are accepted for Hacktoberfest as I've added the necessary tags.

Would you like to contribute? You can create an issue & add more hidden gems or features. This is the current site: https://nisoojadhav.github.io/resources/

**Comment by aakarsh-2004** [comment]
I would love to contribute!

**Pull request merged**
